version: "3.7"
services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"
    ports:
      - "8000:80"